### ISSUE TITLE
You have my username

### ISSUE THREAD

**Issue by TheComet** [TheComet-zz/EasyRanking#1]
Hi!

Could you possibly transfer your account to me? I'd really like to have "TheComet" and not "TheComet93" if that's no problem with you.

**Comment by eugeneko** [comment]
@TheComet93 the guy is TheComet-zz now, why don't you change the name?

**Comment by TheComet** [comment]
Thanks for the hint @eugeneko! Behold, my final form. I, TheComet, have arisen.
